### ISSUE TITLE
Nice work! Would you like to add the histograms that you used to compute the entropy to the paper?

### ISSUE THREAD

**Issue by StarCycle** [bdaiinstitute/theia#1]
Hello @jshang-bdai @bmay-bdai,

It's a really nice work! Limited training but strong performance!

Since the entropy of L2 norms of the patch tokens are a good indicator of robitics manipulation success rate, would you like to add the histograms that you used to compute the entropy to the appendix of the paper?

The entropy is a scaler. If you add the histograms, we may find more clues about why the entropy matters. Different histogram distributions can all lead to high entropy, and I want to check which distribution they actually are. **If possible, the histograms should have the same range and without clipping the outliers.**

The L2 norm maps are provided but cannot show that clearly...

Again it's a really nice work and thank you for making it open-source!

Best wishes,
StarCycle

**Comment by elicassion** [comment]
Hi @StarCycle,

Thank you for carefully reading and thinking on the analysis. 

We totally agree the pattern give more details. To this end, we did investigate the distributions of the entropies. Below we show the histogram of the feature norm entropy of 4 selected models: ViT-B, DINOv2-B, VC-1-B, and Theia-B (called `rvfm_deit_base_4features` in the legend).

Quick takeaway from the plots: Theia has the most balanced distribution of the feature norm, while the others are long-tailed. ViT-B has two peaks in the histogram. VC-1 is extremely centered and heavily long-tailed. DINOv2 is relatively less long-tailed than ViT-B and VC-1, and has a relatively nicer distribution around the median value.

We first plot them in the same chart to give an overview of how different they are. There is no clipping as you mentioned.
![image](https://github.com/user-attachments/assets/cdfca376-4c77-4ff9-be6b-519b86fcdd3b)

The plot above gives a nice overview but it is not good for checking the details. So then we plot each model separately: 

ViT-B
![IMG_1342](https://github.com/user-attachments/assets/638a04a0-7cce-4e0c-b17e-7d97e5fc6425)

DINOv2-B
![IMG_1343](https://github.com/user-attachments/assets/91ebc22c-8e87-4fc3-beb3-ef3ce7a8cae1)

VC-1-B
![IMG_1344](https://github.com/user-attachments/assets/8cd291b8-78c5-48b8-a3da-0bd2d0162c21)

Theia-B
![IMG_1345](https://github.com/user-attachments/assets/ab2178ed-c979-4466-adc5-33d89c783058)

**Comment by StarCycle** [comment]
Great thanks! It's more clear to me!

**Comment by COST-97** [comment]
Hello:
Excellent work! 
Could you share the code that achieved these results? 
Thanks!
    

> Hi @StarCycle,
> 
> Thank you for carefully reading and thinking on the analysis.
> 
> We totally agree the pattern gives more details. To this end, we did investigate the distributions of the entropies. Below we show the histogram of the feature norm entropy of 4 selected models: ViT-B, DINOv2-B, VC-1-B, and Theia-B (called `rvfm_deit_base_4features` in the legend).
> 
> Quick takeaway from the plots: Theia has the most balanced distribution of the feature norm, while the others are long-tailed. ViT-B has two peaks in the histogram. VC-1 is extremely centered and heavily long-tailed. DINOv2 is relatively less long-tailed than ViT-B and VC-1, and has a relatively nicer distribution around the median value.
> 
> We first plot them in the same chart to give an overview of how different they are. There is no clipping as you mentioned. ![image](https://private-user-images.githubusercontent.com/11537907/353503547-cdfca376-4c77-4ff9-be6b-519b86fcdd3b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyODkzNzAsIm5iZiI6MTcyNDI4OTA3MCwicGF0aCI6Ii8xMTUzNzkwNy8zNTM1MDM1NDctY2RmY2EzNzYtNGM3Ny00ZmY5LWJlNmItNTE5Yjg2ZmNkZDNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDAxMTExMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhN2VkOTliZDFhMzg3MmI4MDNhNjU3YzEwMWM5MGYxYzVjOGQyODgwMzk3ZGQwZTk2MTA4OWEzNzg3Y2Y0OWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Th8QwVJPgU2GPDKCH5uEfDWfWmEowkTnj9WfjJYS-b8)
> 
> The plot above gives a nice overview but it is not good for checking the details. So then we plot each model separately:
> 
> ViT-B ![IMG_1342](https://private-user-images.githubusercontent.com/11537907/353505088-638a04a0-7cce-4e0c-b17e-7d97e5fc6425.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyODkzNzAsIm5iZiI6MTcyNDI4OTA3MCwicGF0aCI6Ii8xMTUzNzkwNy8zNTM1MDUwODgtNjM4YTA0YTAtN2NjZS00ZTBjLWIxN2UtN2Q5N2U1ZmM2NDI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDAxMTExMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjZGU5ODFiMjFlM2RkZDcwZGVlZWI2MDMyMDdkOGM4ZWU4OTJmM2MyYzMwMjA5ZDhmNzFhYzYxYzNjN2JhOWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QlKqY3yo7vUTfNu42qApH3bDof_KIP1Ks_zmENYtuoQ)
> 
> DINOv2-B ![IMG_1343](https://private-user-images.githubusercontent.com/11537907/353505200-91ebc22c-8e87-4fc3-beb3-ef3ce7a8cae1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyODkzNzAsIm5iZiI6MTcyNDI4OTA3MCwicGF0aCI6Ii8xMTUzNzkwNy8zNTM1MDUyMDAtOTFlYmMyMmMtOGU4Ny00ZmMzLWJlYjMtZWYzY2U3YThjYWUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDAxMTExMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmM2RhNzc2ZDliZDAxNWMzMzMwNWVmNTdjZTE4Y2Q4YzQ4ZGVmN2MyYWQ2MjQyZmM0NzQ0Y2Y0YmQ3NDNjZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ThU7YV4WcvRONOXkxwwwADL0E96RiV-6mpLWLOS5ZUI)
> 
> VC-1-B ![IMG_1344](https://private-user-images.githubusercontent.com/11537907/353505281-8cd291b8-78c5-48b8-a3da-0bd2d0162c21.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyODkzNzAsIm5iZiI6MTcyNDI4OTA3MCwicGF0aCI6Ii8xMTUzNzkwNy8zNTM1MDUyODEtOGNkMjkxYjgtNzhjNS00OGI4LWEzZGEtMGJkMmQwMTYyYzIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDAxMTExMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1YTc3MDAyZDY3ODk2MzJhNmIwMmNmYTdhMWIxN2Y4NTdmYjgxN2FiOGZhMzNkYmM0ZjU0ZDViMWVhZjhkMTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.l--UjIduGoeAOL0iYsv0_UOgKXxZX0XXzjuqF2cmAsE)
> 
> Theia-B ![IMG_1345](https://private-user-images.githubusercontent.com/11537907/353505341-ab2178ed-c979-4466-adc5-33d89c783058.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyODkzNzAsIm5iZiI6MTcyNDI4OTA3MCwicGF0aCI6Ii8xMTUzNzkwNy8zNTM1MDUzNDEtYWIyMTc4ZWQtYzk3OS00NDY2LWFkYzUtMzNkODljNzgzMDU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDAxMTExMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0OTQ4Y2E0NDhhNTBjODAzZWNiMzJkNzkzMTRiZjVhYzZhMjRjYzU3ZTQ3ZmVmZjdlNjgzMDEyOGFkMWVhM2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1006xnzDz1pF_rAYYTALaKEqwKt92uoiupklJxaBaPY)

**Comment by elicassion** [comment]
Hi @COST-97 

Sorry for the late reply. The details are available in Section 5 and Appendix G of the paper. At the moment this part of the code is not considered for open-sourcing, but I can share a bit more about how this is implemented. We use `np.histogram` to discretize the distribution and then use `scipy.stats.entropy` to calculate the entropy.
