### ISSUE TITLE
more pre-trained model

### ISSUE THREAD

**Issue by fishfuck** [bdaiinstitute/theia#13]
Hi！Thanks for your great work ! ! ! !
I have successfully reproduced your work locally, and I plan to do some downstream tasks based on your work. However, the depth weights available are only for `theia-tiny-patch16-224-cddsv`, and depth is quite important for my task. Could you possibly open-source more pre-trained weights related to depth, such as the small or base versions?
Looking forward to your reply.

**Comment by jshang-bdai** [comment]
Hi,

Thanks for your interest! We are considering this request and hopefully will update you early next week.

**Comment by jshang-bdai** [comment]
Hi @fishfuck

We have released two larger models, `small` and `base` trained on all five teachers. Have fun!

- small https://huggingface.co/theaiinstitute/theia-small-patch16-224-cddsv
- base https://huggingface.co/theaiinstitute/theia-base-patch16-224-cddsv
