### ISSUE TITLE
some problems

### ISSUE THREAD

**Issue by sunhan1997** [bdaiinstitute/theia#14]
hello, I try to run this code by hugeface,but get some error:
```
UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
Some weights of ViTModel were not initialized from the model checkpoint at facebook/deit-base-patch16-224 and are newly initialized: ['vit.pooler.dense.bias', 'vit.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Fast image processor class <class 'transformers.models.vit.image_processing_vit_fast.ViTImageProcessorFast'> is available for this model. Using slow image processor class. To use the fast image processor class set `use_fast=True`.
```

In addition, how can i get the checkpoint?

**Comment by elicassion** [comment]
Hi @sunhan1997 

The TypedStorage thing is a warning and you can ignore it.

The Fast image processor is a new feature from huggingface and is optional. In the current code release we don’t use it.

To get pre-trained checkpoints, you can follow our [quick start guide](https://github.com/bdaiinstitute/theia?tab=readme-ov-file#quick-start-use-pre-trained-theia-models) or visit https://huggingface.co/collections/theaiinstitute/theia-66a7a6ae80a707547c358cce
