### ISSUE TITLE
dataset preprocessing issue

### ISSUE THREAD

**Issue by zhlhlhlhl** [bdaiinstitute/theia#6]
More than impressive work!!
I have finished the first step of transferring the imagenet to webdataset format. But before the _Feature Extraction_ , it should be split and get the _splits.json_. I check the [split_dataset.py](https://github.com/bdaiinstitute/theia/blob/main/src/theia/scripts/preprocessing/split_dataset.py),  the annotation shows # all_datasets.update(ALL_IMAGE_DATASETS) imagenet has its own splits, can be done separately. So how can I get the splits.json for imagenet dataset. I think there are some steps missing in the README.

**Comment by elicassion** [comment]
Hi @zhlhlhlhl,

Thanks for your interest to our work.

For ImageNet (ImageNet-1K), we use the official train/val splits.  You can directly write down `splits.json` according to the number of images in each split. That is:
```
{
    "train": 1281167,
    "val": 50000
}
```
if I remember the numbers correctly. Let me know if it does not work.

**Comment by zhlhlhlhl** [comment]
Thanks for your prompt reply! it works.
