### ISSUE TITLE
pre-trained model

### ISSUE THREAD

**Issue by yangfan293** [bdaiinstitute/theia#8]
Thank you very much for your excellent work! We tried to use the pre-trained parameters you provided to extract depth features, but it seems that the pre-trained model you provided does not include depth-anything. Could you please provide the pre-trained models which include depth-anything?
<img width="773" alt="微信图片_20240821232705" src="https://github.com/user-attachments/assets/49c19efc-cd0a-42dd-b72d-42bb8e98e342">

**Comment by elicassion** [comment]
Hi @yangfan293 

Thanks for your interest on our work! 

`theaiinstitute/theia-tiny-patch16-224-cddsv` model is trained on teachers including `SAM` and `Depth-Anything`. Please use this model to generate Depth-Anything features.

**Comment by yangfan293** [comment]
![image](https://github.com/user-attachments/assets/3d82a084-c8f6-4725-bf66-7a002bf15adf)
Thanks for your quick reply. I have another question. What does ground truth mean in the Demo you provided? Is this the effect of the Depth-anything model? If yes, it looks better than Theia, and if not, how did that come about?

**Comment by elicassion** [comment]
It's from Depth-Anything.
